config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :chat_rooms do
    resources :messages
  end

  # Optionally, you can add a root route
  root 'chat_rooms#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_room.rb
# frozen_string_literal: true

class ChatRoom < ApplicationRecord
  has_many :messages

  validates :name, presence: true
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/chat_rooms_controller.rb
# frozen_string_literal: true

class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = ChatRoom.new(chat_room_params)
    if @chat_room.save
      redirect_to chat_room_path(@chat_room), notice: 'Chat room was successfully created.'
    else
      render :new
    end
  end

  def show
    @chat_room = ChatRoom.find(params[:id])
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:name)
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  def create
    @chat_room = ChatRoom.find(params[:chat_room_id])
    @message = @chat_room.messages.new(message_params)
    @message.user = current_user # Assuming you have user authentication

    if @message.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to chat_room_path(@chat_room) }
      end
    else
      render 'chat_rooms/show' # Handle error case
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/chat_rooms/index.html.erb
<h1>Chat Rooms</h1>

<%= link_to 'New Chat Room', new_chat_room_path %>

<ul>
  <% @chat_rooms.each do |chat_room| %>
    <li><%= link_to chat_room.name, chat_room_path(chat_room) %></li>
  <% end %>
</ul>

app/views/chat_rooms/new.html.erb
<h1>New Chat Room</h1>

<%= form_with model: @chat_room, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit 'Create Chat Room' %>
  </div>
<% end %>

app/views/chat_rooms/show.html.erb
<h1><%= @chat_room.name %></h1>

<h2>Messages</h2>
<div id="messages">
  <%= render @chat_room.messages %>
</div>

<h3>Send a Message</h3>
<%= form_with(model: [@chat_room, Message.new], local: false) do |form| %>
  <div>
    <%= form.label :content %>
    <%= form.text_area :content, rows: 3 %>
  </div>
  <div>
    <%= form.submit 'Send Message' %>
  </div>
<% end %>

<%= link_to 'Back to Chat Rooms', chat_rooms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div>
  <strong><%= message.user.email %>:</strong> <%= message.content %>
</div>

app/views/messages/create.turbo_stream.erb
<turbo-stream action="append" target="messages">
  <template>
    <div><strong><%= @message.user.email %>:</strong> <%= @message.content %></div>
  </template>
</turbo-stream>